Set up Node.js environment and add testing step to workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,5 +6,19 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-      - name: Print text from index.js
-        run: cat dist/index.js
+      - name: set up nodejs
+        uses: actions/setup-node@v2
+        with:
+          node-version: '18'
+
+      - name: install package json
+        run: npm install
+
+      - name: Run testing
+        run: |
+          output=$(node dist/Test1.js)
+
+          if [ $output -ne 0 ]; then
+            echo "Error: code $output"
+            exit 1
+          fi
